'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AIOminer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _STOP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_STOP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property AIO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AIO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property AIO_GREEN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AIO_GREEN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property aio_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aio_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property AIO_RED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AIO_RED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property AIO_RED_STOP1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AIO_RED_STOP1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property aiominer_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aiominer_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property azzz() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("azzz", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property beecool() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beecool", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property BitcoinGold_Icon_yelow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BitcoinGold-Icon-yelow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property bitcoingold_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bitcoingold_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property bitcoinz_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bitcoinz_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property BTG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BTG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property bytecoin_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bytecoin_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property electroneum_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("electroneum_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ellaism_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ellaism_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ETC2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ETC2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ETH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ETH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ethereum_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ethereum_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ethereumclassic_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ethereumclassic_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property exodus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exodus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property expanse_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("expanse_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property feathercoin_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feathercoin_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property halcyon_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("halcyon_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property hush_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hush_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property karbo_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("karbo_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property komodo_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("komodo_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property logo1_transparent_welcome() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo1_transparent_welcome", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property logo1_transparent_welcome_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo1_transparent_welcome_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property metaverse_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("metaverse_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property monacoin_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("monacoin_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property monero_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("monero_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property MrMiner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MrMiner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property musicoin_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("musicoin_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property neutral() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("neutral", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property nvidia_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nvidia_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property orbitcoin_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orbitcoin_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property pirl_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pirl_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property redx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property shovel_med() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shovel_med", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property START() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("START", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property straks_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("straks_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property sumokoin_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sumokoin_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property trezarcoin_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trezarcoin_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ubiq_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ubiq_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property verge_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("verge_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property vertcoin_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vertcoin_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property vivo_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vivo_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property votecoin_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("votecoin_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property zcash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zcash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property zcash_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zcash_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property zcash1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zcash1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property zclassic_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zclassic_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property zencash_logo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zencash_logo_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
